#!/usr/bin/env bash

command=$(basename "$0")
update_url="For updates visit: https://github.com/sbriskin/rudate"

# Functions
display_version() {
    cat << EOF

Russian Date Format v1.0

Copyright (C) 2014 Sergey Briskin <sergey@briskin.org>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

$update_url
EOF
}

display_help() {
    cat << EOF

Usage: $command [-c] [--color] [-h] [--help] [--version]

Options:
         -c, --color - Colorify output (blue saturday, red sunday)
         -h, --help  - Show this help
         --version   - Show version and license info

EOF
}

rus(){
	case "$month" in
		01)	month="января" ;;
		02)	month="февраля" ;;
		03)	month="марта" ;;
		04)	month="апреля" ;;
		05)	month="мая" ;;
		06)	month="июня" ;;
		07)	month="июля" ;;
		08)	month="августа" ;;
		09)	month="сентября" ;;
		10)	month="октября" ;;
		11)	month="ноября" ;;
		12)	month="декабря" ;;
		*)	printf "ERROR: unknown data $month \n" 1>&2 ; exit 1 ;;
	esac

	case "$weekday" in
		1)	weekday="$WhiteПонедельник$NC" ;;
		2)	weekday="$WhiteВторник$NC" ;;
		3)	weekday="$WhiteСреда$NC" ;;
		4)	weekday="$WhiteЧетверг$NC" ;;
		5)	weekday="$WhiteПятница$NC" ;;
		6)	weekday="$LBlueСуббота$NC" ;;
		7)	weekday="$LRedВоскресенье$NC" ;;
		*)	printf "ERROR: unknown data $weekday \n" 1>&2 ; exit 1 ;;
	esac			
}

colorify(){
	White='\e[1;37m'  # White
	LGray='\e[0;37m'  # Light Gray 
	Yellow='\e[1;33m' # Yellow
	DRed='\e[0;31m'   # Dark red
	LRed='\e[1;31m'   # Light red
	DBlue='\e[0;34m'  # Dark blue
	LBlue='\e[1;34m'  # Light blue
	NC='\e[0m'        # Disable Color
}

# Parse command-line options
while [ $# -gt 0 ]; do
    case "$1" in
    -c|--color)
		colorify
        shift ;;   
    -h|--help)
		display_help
		exit 0 ;;
    --version)
		display_version
		exit 0 ;;
    -*)
        echo "unrecognized option "\`"$1'"
        display_help
        exit 1 ;;
    *)  
		break ;;
    esac
done

date=$(date +%d)
month=$(date +%m)
year=$(date +%Y)
weekday=$(date +%u)
time=$(date +%T)
tzone=$(date +%Z)
rus

printf "$weekday,$Yellow $date $month $year,$White $time $LGray($tzone)$NC\n"

exit 0
